### PR TITLE
Scala js support

### PR DESCRIPTION
**Pull request by cquiroz**
In the context of https://github.com/http4s/http4s/issues/956 I need `http4s-websocket` to support scala.js. This PR updates the build to achieve that by converting the project to `crossProject` and moving some files around.

I'm also updating the set of scala versions supported to match `http4s`

Three question remain open:

* There is a single java file which is not at the moment made available to the js side. We don't need it for https://github.com/http4s/http4s/issues/956 as we are only trying to compile core but it should be doable as `scala.js` supports. Do you think is worth converting `FrameTranscoder` to scala?
* I haven't used the typelevel compiler. I have seen some issues with `typelevel` and `scala.js` and should clarify that first
* Tests are based on `specs2` which isn't available for scala.js

### CODE REVIEW

**Comment by rossabaker** [comment]
Sorry, this one slipped through my notifications.

I have no idea why `FrameTranscoder` is implemented in Java.  I don't see any reason it has to be.

There shouldn't be any problem compiling with Lightbend Scala.  Several of http4s' dependencies already are.  Though I'm curious what issues there are on scala.js, because that's going to be an issue for the port of pieces of http4s to scala.js.

Specs2 is fine for now.  It sucks to only test on one platform, but I don't want to move all our tests to ScalaTest, given that scala.js support is coming for specs2.

**Comment by cquiroz** [comment]
maybe i'll port `FrameTranscoder`then. I have to still clarify the issue with the typelevel compiler, it affects one of my projects but it maybe a separate issue

I agree on just using specs2. Scala.js for http4s is still very preliminar

**Comment by bryce-anderson** [comment]
I can't recall why I chose Java, but I don't see an obvious reason for it to be in java. Best guess: everything is pretty stateful and Java-ish so maybe it just felt right.

Feel free to port it.

**Comment by cquiroz** [comment]
Ported FrameTrascoder to scala. I want to also port this to support scala.js 1.0.0-M1 but that's for a future enhancement

**Review by rossabaker — APPROVED** [review]
I didn't go line-by-line, but nothing jumps out as wrong and the tests pass.

**Comment by cquiroz** [comment]
Could you merge this and make a release to continue testing the scala.js integration on http4s?

**Comment by rossabaker** [comment]
Released as v0.2.0.

**Comment by cquiroz** [comment]
Thanks a lot

**Pull request merged**
